export const VALIDATION = {
  PASSWORD_MIN_LENGTH: 6,

  PASSWORD_MAX_LENGTH: 30,

  NAME_MIN_LENGTH: 2,

  NAME_MAX_LENGTH: 20,

  EMAIL_MAX_LENGTH: 254,

  BCRYPT_SALT_ROUNDS: 10,

  TITLE_MAX_LENGTH: 100,

  DESCRIPTION_MAX_LENGTH: 500,

  BULK_TODOD_MAX_LENGTH: 50,
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

export const PAGINATION = Object.freeze({
  DEFAULT_PAGE: 1,
  MAX_LIMIT: 999,
});
